#!/usr/bin/env bash
# Start breathe-helper at macOS login (no npm run dev required).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
HELPER="$ROOT/assets/breathe-helper"
CONFIG="$HOME/Library/Application Support/com.raycast.breathe/login-config.json"
PLIST_LABEL="com.raycast.breathe.login"
PLIST_PATH="$HOME/Library/LaunchAgents/${PLIST_LABEL}.plist"
WRAPPER="$ROOT/scripts/login-start.sh"

if [[ ! -x "$HELPER" ]]; then
  echo "error: breathe-helper not found. Run: npm run build-swift" >&2
  exit 1
fi

if [[ ! -f "$CONFIG" ]]; then
  echo "error: no login-config.json yet." >&2
  echo "Start breathing once from Raycast (Toggle or Start) to save your pattern and displays." >&2
  exit 1
fi

cat > "$WRAPPER" << EOF
#!/usr/bin/env bash
# Auto-generated by install-login-agent.sh
CONFIG="\$HOME/Library/Application Support/com.raycast.breathe/login-config.json"
HELPER="$HELPER"
PID_FILE="\$HOME/Library/Application Support/com.raycast.breathe/breathe-helper.pid"

if [[ -f "\$PID_FILE" ]]; then
  pid=\$(cat "\$PID_FILE" 2>/dev/null || true)
  if [[ -n "\$pid" ]] && kill -0 "\$pid" 2>/dev/null; then
    exit 0
  fi
fi

# Wait for displays after login
sleep 3
exec "\$HELPER" --config "\$CONFIG"
EOF
chmod +x "$WRAPPER"

mkdir -p "$HOME/Library/LaunchAgents"

cat > "$PLIST_PATH" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${PLIST_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${WRAPPER}</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>StandardOutPath</key>
  <string>${HOME}/Library/Application Support/com.raycast.breathe/login-agent.log</string>
  <key>StandardErrorPath</key>
  <string>${HOME}/Library/Application Support/com.raycast.breathe/login-agent.log</string>
</dict>
</plist>
EOF

launchctl bootout "gui/$(id -u)/${PLIST_LABEL}" 2>/dev/null || true
launchctl bootstrap "gui/$(id -u)" "$PLIST_PATH"

echo "Installed login auto-start: ${PLIST_LABEL}"
echo "Uses config: ${CONFIG}"
echo "Helper: ${HELPER}"
echo "Logs: ~/Library/Application Support/com.raycast.breathe/login-agent.log"
